/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    {
      type: 'category',
      collapsible: true,
      collapsed: false,
      label: 'Getting Started',
      link: {
        type: 'generated-index',
        title: 'Getting Started 🔧',
        description: 'Get started learning about Arc and how best to make use for it',
        slug: '01-Getting Started'
      },
      items: [{
        type: 'autogenerated',
        dirName: '01-Getting Started'
      }],
    },
    {
      type: 'category',
      collapsible: true,
      collapsed: true,
      label: 'Advanced',
      link: {
        type: 'generated-index',
        title: 'Advanced Configuration',
        description: 'Get more into the weeds of Arc configuration',
        slug: '02-Advanced',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '02-Advanced'
        },
        {
          type: 'category',
          collapsible: true,
          collapsed: true,
          label: 'ADR',
          link: {
            type: 'generated-index',
            title: 'ADR',
            description: 'Architectural Decision Records',
            slug: '05-ADR'
          },
          items: [
            {
              type: 'autogenerated',
              dirName: '05-ADR'
            }
          ],
        }
        
      ],
    },
    {
      type: 'category',
      collapsible: true,
      collapsed: true,
      label: 'Gateway',
      link: {
        type: 'generated-index',
        title: 'Arc Gateway',
        description: 'More information on how the Arc Gateway works',
        slug: '03-Gateway'
      },
      items: [{
        type: 'autogenerated',
        dirName: '03-Gateway'
      }],
    },
    {
      type: 'category',
      collapsible: true,
      collapsed: true,
      label: 'Agent',
      link: {
        type: 'generated-index',
        title: 'Arc Agent',
        description: 'More information on how the Arc Agent works',
        slug: '04-Agent'
      },
      items: [{
        type: 'autogenerated',
        dirName: '04-Agent'
      }],
    },
  ]

  
};

export default sidebars;
